name: new_media_releases
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # adobe_xd: ^1.0.0+1
  intl: ^0.16.1
  pull_to_refresh: ^1.6.1
  google_fonts: ^1.1.0
  url_launcher: ^5.7.2
  curved_navigation_bar: ^0.3.4 #latest version
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  slide_countdown_clock: ^1.0.3
  collection: ^1.14.12
  flutter_local_notifications: ^3.0.2
  sticky_infinite_list: ^3.0.0
  material_design_icons_flutter: 4.0.5555
  sqflite: any
  cached_network_image: ^2.3.2+1
  firebase_dynamic_links: ^0.6.3
  share: '>=0.6.5+4 <2.0.0'
  flutter_native_timezone: ^1.0.4
  #flutter_localized_countries: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/fonts/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
